// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eclvlcnnkacjwjdjgdyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbHZsY25ua2FjandqZGpnZHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTA0NjksImV4cCI6MjA3Mzg4NjQ2OX0.3pJwpNVk12VTDl6vojrhnkcAA-DtNsbVsbNcq5N3KLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});